### ISSUE TITLE
[FEATURE] Inappropriate Footer Displayed Instead of PageNotFound for Incorrect URL

### ISSUE THREAD

**Issue by Saurav-Pant** [Frenziecodes/Projest#101]
### Description

When a user enters an incorrect URL type, instead of being redirected to a proper PageNotFound page, the website displays the footer. This creates a confusing user experience as users expect to see an informative PageNotFound page, providing guidance and relevant information about the error

### Describe the solution you'd like

 Implement a proper PageNotFound page to replace the inappropriate footer display when users enter an incorrect URL type. Provide clear error messaging and helpful navigation options to improve the user experience. 

### Screenshots

https://github.com/Frenziecodes/Projest/assets/103263909/7d2382c1-ce53-4b6a-a29c-c741caa6ccac

**Comment by Frenziecodes** [comment]
Fixed! Thanks for bringing this to our attention. We appreciate your help in identifying and resolving the issue.
