### ISSUE TITLE
Squeezed image in hero section

### ISSUE THREAD

**Issue by shobhitexe** [Frenziecodes/Projest#107]
### Description

Hey as we can see on attached SS the image is looking very squeezed in hero section and also hero section needs bit more gap from above

### Screenshots

![image](https://github.com/Frenziecodes/Projest/assets/29349136/be0215ef-b5f4-4218-8ab2-431c4277b0c7)

![image](https://github.com/Frenziecodes/Projest/assets/29349136/fa6c122d-5c99-413a-9e32-a6da2568e475)

**Comment by Frenziecodes** [comment]
Thanks @shobhitexe  fixing this as soon as possible

**Comment by Frenziecodes** [comment]
Yeah that's the desired behavior. Thanks 🎉
