### ISSUE TITLE
Create a navbar logo

### ISSUE THREAD

**Issue by Petrosdevri** [Frenziecodes/Projest#44]
**Is your feature request related to a problem? Please describe.**
Most websites have a professional logo embedded in their navbars. A great idea would be to do the same here. 

**Describe the solution you'd like**
A logo which replaces the word Projest, either minimalistic (like a P with an icon) or the same word with better styling.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by lewisushindi** [comment]
@Petrosdevri  thank you for contributing to this project. I will be implementing the logo as soon as possible.

**Comment by lewisushindi** [comment]
@Petrosdevri the project is being switched to react. Once that is done we can start working on the navbar logo

**Comment by Fax-ofJax** [comment]
So, I can see that I can contribute to this project by creating a navbar. So, can I ask you to assign this work for me? (If no one is working on this)

**Comment by lewisushindi** [comment]
Hello @Petrosdevri, just wanted to let you know that we've finished transitioning the project to React. I was wondering if we could chat about the design of the navbar logo. Are you available to discuss this sometime?

**Comment by Petrosdevri** [comment]
Yes, sure.
