### ISSUE TITLE
[DOCS] <Add Contributing steps>

### ISSUE THREAD

**Issue by jayk-gupta** [Frenziecodes/Projest#96]
### Description

How to add my project in it?

**Comment by munnokd** [comment]
Hey @jayk-gupta  are you want to add this section to this project? Let me know so I will assign to you other wise I can start work on this issue.

**Comment by jayk-gupta** [comment]
Yeah!
Assign to me!

**Comment by lewisushindi** [comment]
@jayk-gupta  done, assigned the issue to you

**Comment by Frenziecodes** [comment]
Hello @jayk-gupta I have added the contribution steps using this [ commit](https://github.com/Frenziecodes/Projest/commit/83d6beddcd202a6e2c43e9b7aa15ba5badb886dc!) Thanks for bringing this to our attention. We appreciate your help in identifying and resolving the issue.
