### ISSUE TITLE
[doc]: issue form's footer link needs to be update with new username

### ISSUE THREAD

**Issue by kumarsonsoff3** [Frenziecodes/Projest#99]
### What would you like to share?

Since you've recently changed your username. We need to update it in the issue forms. All others are updated by you, but the `documentation` issue form still needs to be updated! 

------
![image](https://github.com/Frenziecodes/Projest/assets/88786642/311eae92-f738-4055-a7a1-1b0b9553bf38)

**Comment by Frenziecodes** [comment]
Thank you, @kumarsonsoff3! I will promptly update the documentation issue form

**Comment by Frenziecodes** [comment]
done
